export const driftKeyframes = [
  {
    position:0,
    duration:1,
    brightness:1.0,
    contrast:1.0,
    saturation:1.0,
    hue:0,
    redGain:1.0,
    greenGain:1.0,
    blueGain:1.0,
    gamma:1.0
  },
  {
    position:0.333,
    duration:1,
    brightness:0.94,
    contrast:1.16,
    saturation:1.18,
    hue:172,
    redGain:0.82,
    greenGain:1.02,
    blueGain:1.38,
    gamma:1.06
  },
  {
    position:0.667,
    duration:1,
    brightness:1.06,
    contrast:1.22,
    saturation:1.28,
    hue:42,
    redGain:1.36,
    greenGain:0.94,
    blueGain:0.88,
    gamma:0.96
  },
  {
    position:1,
    duration:1,
    brightness:0.98,
    contrast:0.96,
    saturation:0.92,
    hue:-26,
    redGain:1.04,
    greenGain:1.12,
    blueGain:0.96,
    gamma:1.12
  }
];

export const driftPresets = {
  "Analog Fade":{
    speed:0.000088,
    amount:24,
    morphSmooth:"smoothstep",
    saturationBias:4,
    contrastBias:5,
    gammaBias:1.08,
    brightnessBias:0,
    hueBias:0,
    paletteAmount:10,
    paletteBlend:"soft-light",
    jitter:2,
    momentum:42,
    driftNoise:9,
    loopMode:"pingpong",
    seed:2409,
    keyframes:[
      {
        brightness:0.98,
        contrast:1.0,
        saturation:0.98,
        hue:-12,
        redGain:1.04,
        greenGain:1.0,
        blueGain:0.98,
        gamma:1.06,
        paletteAmount:8,
        paletteBlend:"soft-light",
        paletteColor:"#ffe1bd"
      },
      {
        brightness:1.02,
        contrast:1.06,
        saturation:1.08,
        hue:18,
        redGain:1.08,
        greenGain:0.98,
        blueGain:0.95,
        gamma:1.1,
        paletteAmount:12,
        paletteBlend:"soft-light",
        paletteColor:"#ffd0a0"
      },
      {
        brightness:0.99,
        contrast:1.03,
        saturation:1.02,
        hue:-4,
        redGain:1.02,
        greenGain:1.02,
        blueGain:0.98,
        gamma:1.08,
        paletteAmount:9,
        paletteBlend:"soft-light",
        paletteColor:"#fff0d8"
      }
    ]
  },
  "Ambient Flow":{
    speed:0.000092,
    amount:56,
    morphSmooth:"sine",
    saturationBias:18,
    contrastBias:-8,
    gammaBias:1.12,
    brightnessBias:0,
    hueBias:0,
    paletteAmount:28,
    paletteBlend:"soft-light",
    jitter:0,
    momentum:72,
    driftNoise:8,
    loopMode:"pingpong",
    seed:5280,
    keyframes:[
      {
        brightness:0.94,
        contrast:0.92,
        saturation:1.22,
        hue:-34,
        redGain:0.86,
        greenGain:1.02,
        blueGain:1.36,
        gamma:1.18,
        paletteAmount:26,
        paletteBlend:"soft-light",
        paletteColor:"#4e8dff"
      },
      {
        brightness:1.06,
        contrast:0.88,
        saturation:1.26,
        hue:48,
        redGain:1.28,
        greenGain:1.12,
        blueGain:0.84,
        gamma:1.22,
        paletteAmount:32,
        paletteBlend:"soft-light",
        paletteColor:"#ffc15f"
      },
      {
        brightness:1.02,
        contrast:0.84,
        saturation:1.34,
        hue:142,
        redGain:0.78,
        greenGain:1.28,
        blueGain:1.02,
        gamma:1.2,
        paletteAmount:30,
        paletteBlend:"soft-light",
        paletteColor:"#62ffd0"
      },
      {
        brightness:1.04,
        contrast:0.9,
        saturation:1.26,
        hue:-92,
        redGain:1.12,
        greenGain:0.84,
        blueGain:1.34,
        gamma:1.22,
        paletteAmount:32,
        paletteBlend:"soft-light",
        paletteColor:"#b576ff"
      },
      {
        brightness:0.98,
        contrast:0.94,
        saturation:1.24,
        hue:8,
        redGain:1.22,
        greenGain:0.96,
        blueGain:0.9,
        gamma:1.16,
        paletteAmount:26,
        paletteBlend:"soft-light",
        paletteColor:"#ff9c7b"
      }
    ]
  },
  "VHS Mood":{
    speed:0.000118,
    amount:42,
    morphSmooth:"smoothstep",
    saturationBias:24,
    contrastBias:14,
    gammaBias:1.12,
    brightnessBias:-2,
    hueBias:-8,
    paletteAmount:24,
    paletteBlend:"multiply",
    jitter:11,
    momentum:42,
    driftNoise:24,
    loopMode:"pingpong",
    seed:1987,
    keyframes:[
      {
        brightness:0.96,
        contrast:1.12,
        saturation:1.08,
        hue:-18,
        redGain:1.12,
        greenGain:0.94,
        blueGain:0.86,
        gamma:1.14
      },
      {
        brightness:0.9,
        contrast:1.22,
        saturation:1.2,
        hue:172,
        redGain:0.78,
        greenGain:1.04,
        blueGain:1.34,
        gamma:1.2
      },
      {
        brightness:1.02,
        contrast:1.08,
        saturation:1.16,
        hue:32,
        redGain:1.26,
        greenGain:0.98,
        blueGain:0.9,
        gamma:1.08
      }
    ]
  },
  "Toxic Drift":{
    speed:0.000186,
    amount:55,
    morphSmooth:"sine",
    saturationBias:60,
    contrastBias:12,
    gammaBias:1.0,
    brightnessBias:0,
    hueBias:90,
    paletteAmount:45,
    paletteBlend:"overlay",
    jitter:18,
    momentum:18,
    driftNoise:35,
    loopMode:"forward",
    seed:4099,
    keyframes:[
      {
        brightness:1.02,
        contrast:1.12,
        saturation:1.35,
        hue:88,
        redGain:0.8,
        greenGain:1.38,
        blueGain:0.98,
        gamma:0.98
      },
      {
        brightness:0.98,
        contrast:1.2,
        saturation:1.52,
        hue:-122,
        redGain:1.42,
        greenGain:0.88,
        blueGain:1.3,
        gamma:1.04
      },
      {
        brightness:1.05,
        contrast:1.06,
        saturation:1.28,
        hue:42,
        redGain:1.08,
        greenGain:1.24,
        blueGain:0.78,
        gamma:0.94
      }
    ]
  },
  "City Lights":{
    speed:0.000111,
    amount:40,
    morphSmooth:"sine",
    saturationBias:15,
    contrastBias:15,
    gammaBias:1.2,
    brightnessBias:2,
    hueBias:0,
    paletteAmount:35,
    paletteBlend:"soft-light",
    jitter:6,
    momentum:40,
    driftNoise:22,
    loopMode:"pingpong",
    seed:8080,
    keyframes:[
      {
        brightness:0.96,
        contrast:1.16,
        saturation:1.05,
        hue:-32,
        redGain:0.84,
        greenGain:0.96,
        blueGain:1.36,
        gamma:1.18
      },
      {
        brightness:1.08,
        contrast:1.18,
        saturation:1.22,
        hue:38,
        redGain:1.32,
        greenGain:1.0,
        blueGain:0.9,
        gamma:1.12
      },
      {
        brightness:1.0,
        contrast:1.08,
        saturation:1.18,
        hue:166,
        redGain:0.9,
        greenGain:1.24,
        blueGain:1.18,
        gamma:1.24
      }
    ]
  },
  "Thermal Dream":{
    speed:0.000103,
    amount:50,
    morphSmooth:"smoothstep",
    saturationBias:30,
    contrastBias:0,
    gammaBias:1.8,
    brightnessBias:0,
    hueBias:0,
    paletteAmount:25,
    paletteBlend:"screen",
    jitter:5,
    momentum:55,
    driftNoise:28,
    loopMode:"pingpong",
    seed:6118,
    keyframes:[
      {
        brightness:0.88,
        contrast:1.02,
        saturation:1.28,
        hue:-86,
        redGain:0.72,
        greenGain:1.0,
        blueGain:1.42,
        gamma:1.6
      },
      {
        brightness:1.04,
        contrast:1.12,
        saturation:1.4,
        hue:42,
        redGain:1.44,
        greenGain:1.12,
        blueGain:0.7,
        gamma:1.82
      }
    ]
  },
  "Collapse":{
    speed:0.00072,
    amount:86,
    morphSmooth:"exponential",
    saturationBias:95,
    contrastBias:62,
    gammaBias:0.86,
    brightnessBias:-6,
    hueBias:18,
    paletteAmount:50,
    paletteBlend:"overlay",
    jitter:100,
    momentum:0,
    driftNoise:88,
    loopMode:"random",
    seed:9991,
    keyframes:[
      {
        brightness:0.82,
        contrast:1.62,
        saturation:1.55,
        hue:-148,
        redGain:1.4,
        greenGain:0.72,
        blueGain:1.34,
        gamma:0.82
      },
      {
        brightness:1.18,
        contrast:1.82,
        saturation:1.72,
        hue:64,
        redGain:1.56,
        greenGain:1.28,
        blueGain:0.62,
        gamma:0.76
      },
      {
        brightness:0.72,
        contrast:1.48,
        saturation:1.38,
        hue:178,
        redGain:0.7,
        greenGain:1.28,
        blueGain:1.5,
        gamma:0.94
      },
      {
        brightness:1.08,
        contrast:1.7,
        saturation:1.64,
        hue:-28,
        redGain:1.46,
        greenGain:0.82,
        blueGain:0.94,
        gamma:0.84
      }
    ]
  },
  "Indigo Night":{
    speed:0.000101,
    amount:35,
    morphSmooth:"sine",
    saturationBias:20,
    contrastBias:8,
    gammaBias:1.35,
    brightnessBias:-8,
    hueBias:-30,
    paletteAmount:30,
    paletteBlend:"multiply",
    jitter:3,
    momentum:60,
    driftNoise:16,
    loopMode:"pingpong",
    seed:3003,
    keyframes:[
      {
        brightness:0.92,
        contrast:1.1,
        saturation:1.14,
        hue:-46,
        redGain:0.78,
        greenGain:0.9,
        blueGain:1.42,
        gamma:1.28
      },
      {
        brightness:0.98,
        contrast:1.05,
        saturation:1.24,
        hue:-18,
        redGain:0.9,
        greenGain:0.86,
        blueGain:1.28,
        gamma:1.42
      }
    ]
  },
  "Signal Bloom":{
    speed:0.000237,
    amount:60,
    morphSmooth:"smoothstep",
    saturationBias:22,
    contrastBias:-10,
    gammaBias:1.15,
    brightnessBias:4,
    hueBias:0,
    paletteAmount:45,
    paletteBlend:"screen",
    jitter:12,
    momentum:20,
    driftNoise:30,
    loopMode:"forward",
    seed:1414,
    keyframes:[
      {
        brightness:0.96,
        contrast:0.9,
        saturation:1.08,
        hue:-12,
        redGain:1.08,
        greenGain:0.98,
        blueGain:1.06,
        gamma:1.08
      },
      {
        brightness:1.16,
        contrast:0.86,
        saturation:1.26,
        hue:54,
        redGain:1.34,
        greenGain:1.1,
        blueGain:0.92,
        gamma:1.22
      }
    ]
  }
};

export const driftState = {

  version: 2,

  paletteColor: "#ffffff",

  speed: 0.004,
  phase: 0,
  progress: 0,
  direction: 1,
  loopMode: "pingpong",
  bypass: false,

  amount: 65,
  morphSmooth: "smoothstep",

  hueBias: 0,
  saturationBias: 0,
  contrastBias: 0,
  gammaBias: 1,
  brightnessBias: 0,

  jitter: 0,
  momentum: 0,
  driftNoise: 0,

  paletteAmount: 30,
  paletteBlend: "overlay",
  paletteEditActive: false,

  seed: 2409,
  presetName: "Custom",
  selectedKeyframe: 0,
  keyframes: driftKeyframes.map(keyframe => ({ ...keyframe }))

};
